name: Run Lint and Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: npm lint
        run: |
          npm run lint
        env:
          CI: true
      - name: npm test
        run: |
          npm test
        env:
          CI: true
